package net.wagsn.note.storage.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.wagsn.note.entity.NoteItem;

import net.wagsn.note.storage.db.NoteItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteItemDaoConfig;

    private final NoteItemDao noteItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteItemDaoConfig = daoConfigMap.get(NoteItemDao.class).clone();
        noteItemDaoConfig.initIdentityScope(type);

        noteItemDao = new NoteItemDao(noteItemDaoConfig, this);

        registerDao(NoteItem.class, noteItemDao);
    }
    
    public void clear() {
        noteItemDaoConfig.clearIdentityScope();
    }

    public NoteItemDao getNoteItemDao() {
        return noteItemDao;
    }

}
