// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteServer.Stores;

namespace NoteServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190718100853_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NoteCore.Entitys.Note", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Title")
                        .HasMaxLength(127);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NoteCore.Entitys.NoteUserRelation", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(36);

                    b.Property<string>("UserId")
                        .HasMaxLength(36);

                    b.HasKey("NoteId", "UserId");

                    b.ToTable("NoteUserRelations");
                });

            modelBuilder.Entity("NoteCore.Entitys.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1023);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("NickName")
                        .HasMaxLength(63);

                    b.Property<string>("Password")
                        .HasMaxLength(511);

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
